include $(THEOS)/makefiles/common.mk

TWEAK_NAME = CepheiStatusBar
CepheiStatusBar_FILES = $(wildcard *.x) $(wildcard *.m)
CepheiStatusBar_EXTRA_FRAMEWORKS = Cephei
CepheiStatusBar_CFLAGS = -I..

include $(THEOS_MAKE_PATH)/tweak.mk
