#!/bin/sh
set -e

# Restart cfprefsd to inject CepheiCfprefsd.dylib.
killall cfprefsd 2>/dev/null || true

# Install defaults alternative. This is used so Procursus’s defaults package has higher priority
# over Cephei’s defaults, maintaining compatibility.
if [ "$1" = "configure" ]; then
	update-alternatives --install /var/jb/usr/bin/defaults defaults /var/jb/usr/bin/hbprefs 30
fi

# Tell the package manager to restart system app (SpringBoard) after installation.
if ! [ -z "$CYDIA" ]; then
	read -r fd ver <<EOT
$CYDIA
EOT
	if [ "$ver" -ge 1 ]; then
		echo "finish:restart" >&$fd
	fi
fi

exit 0
